### PR TITLE
Add @coro for group commands

### PR DESCRIPTION
**Pull request by maximoei**

### CODE REVIEW

**Comment by maximoei** [comment]
To ensure result is awaited

**Review by rytilahti — APPROVED** [review]
Hi and thanks for the PR! Have you tested some of these commands on a real device? If it is working, could you update the docstrings having question marks (stop, play visible at least in this)?

**Comment by maximoei** [comment]
Hi,
- Create, Abort and Volume control are working for me currently. 
- Play/Stop/Mute not working, I'm not sure they are source-dependent (using Spotify currently)
Will continue some further tests later this week.

**Comment by rytilahti** [comment]
Okay, some of devices (not only sony) work a bit differently when using with external services, but I'd expect that basic controls would be working just fine no matter what. Anyway, feel free to file new PRs as you see fit :-)

**Pull request merged**
