### PR TITLE
Depend on async_upnp_client >=0.27 and fix UpnpFactory imports

### PR DESCRIPTION
**Pull request by yllar**
https://github.com/StevenLooman/async_upnp_client/commit/593b72ebeda2b6902420fa0bf67bf89ab08876e0 breaks UpnpFactory imports, this should fix it

### CODE REVIEW

**Comment by rytilahti** [comment]
This requires bumping the required `async_upnp_client` version to be `>=0.27`. Would you please modify the pyproject.toml, run `poetry update`, and add the changed files to this PR?

**Comment by yllar** [comment]
Updated

**Comment by rytilahti** [comment]
Linting checks are failing (due to https://github.com/psf/black/issues/2964), please run `pre-commit autoupdate` and commit the precommit file to fix that.

**Comment by yllar** [comment]
third time's a charm? 🤞

**Comment by rytilahti** [comment]
Looks like not yet, you can execute the same checks as the pipeline does by running `pre-commit run -a` locally to make sure it passes :-)

**Comment by yllar** [comment]
`pre-commit run -a` is happy now, let's see whats next!

**Pull request merged**
