### PR TITLE
Change `get_play_info` to return info from all available zones

### PR DESCRIPTION
**Pull request by jwiese**
**Breaking change:** `get_play_info()` returns a list of `PlayInfo` objects instead of a single `PlayInfo`.

---
While working on #49, I discovered that `get_play_info` did not properly handle zones, and instead only returned info for the first zone, so this PR fixes that. I also adjusted the CLI output for `songpal playback` to show the source and output. As far as I can tell, `play_info` is the only place in this API where we can see what input is currently selected for each individual zone.

`get_play_info` now returns a list of `PlayInfo`s rather than a single `PlayInfo`

example return from calling `songpal playback` now looks like this:

` Currently playing: cast:audio on extOutput:zone?zone=1 None (None/None), state STOPPED`
`Currently playing: extInput:source on extOutput:zone?zone=2 None (None/None), state STOPPED`

Side note that there's a bug in my firmware on STR-DN1060, and `state` is often wrong (e.g. it's actually playing but returns STOPPED)

### CODE REVIEW

**Review by rytilahti — CHANGES_REQUESTED** [review]
LGTM after removing the irrelevant changes (adding new files, updating gitignore), thanks :+1: Although this is a breaking change, looks like this code path is not currently used in homeassistant so no change is necessary at their end.

**Comment by jwiese** [comment]
Great, thanks for the quick review! I believe these should be complete now. Looking forward to getting zones working in Home Assistant finally :)

**Review by rytilahti — APPROVED** [review]
LGTM! :+1: Let me know when you wish to get a new release made and I'll prepare one.

**Comment by jwiese** [comment]
ASAP would be great, then I can start integration testing the zone updates
with the home assistant plugin, thanks!

**Comment by rytilahti** [comment]
You can always install a development version (`pip install -e .` in the source directory) for development uses and it's usually better so until you are sure that no other changes are required, but I'll prepare a new release soon-ish :-)

**Pull request merged**
